# Generated by Django 2.2.1 on 2019-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('photo', models.CharField(max_length=150)),
                ('categories', models.TextField()),
            ],
        ),
    ]
