# Generated by Django 2.2.1 on 2019-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190525_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='categories',
            field=models.TextField(default={'architecture': 0, 'art': 0, 'history': 0, 'interesting': 0, 'nature': 0, 'religion': 0, 'war': 0}),
        ),
    ]
